name: Update ReadMe with blog feed

on:
  # schedule:
  #   # Once a day at 0 AM UTC
  #   - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://zwyx.dev/blog/rss.xml
          readme-section: feed
          max: 10
          empty-commits: false
